version: '3.8'

services:
  backend:
    image: ghcr.io/hpy97/proshop_mern-backend:latest
    container_name: proshop-backend
    ports:
      - '5000:5000'
    env_file:
      - .env
    restart: always

  frontend:
    image: ghcr.io/hpy97/proshop_mern-frontend:latest
    container_name: proshop-frontend
    ports:
      - '3000:3000'
    restart: always